name: Build and Test
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron:  '0 7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout azure-javaee-iaas
        uses: actions/checkout@v2
        with:
          repository: galiacheng/azure-javaee-iaas
          path: azure-javaee-iaas        
      - name: Checkout azure-quickstart-templates
        uses: actions/checkout@v2
        with:
          repository: Azure/azure-quickstart-templates
          path: azure-quickstart-templates     
      - name: Checkout arm-oraclelinux-wls-admin
        uses: actions/checkout@v2
        with:
          path: arm-oraclelinux-wls-admin  
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build azure-javaee-iaas
        run: mvn -DskipTests clean install --file azure-javaee-iaas/pom.xml
      - name: Built and test arm-oraclelinux-wls-admin
        run: mvn -Ptemplate-validation-tests clean install --file arm-oraclelinux-wls-admin/pom.xml
      - name: Archive arm-oraclelinux-wls-admin target
        uses: actions/upload-artifact@v1 
        if: success()
        with:
          name: target
          path: arm-oraclelinux-wls-admin/target
