name: Build and Test

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron:  '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout azure-javaee-iaas
        uses: actions/checkout@v2
        with:
          repository: galiacheng/azure-javaee-iaas
          path: azure-javaee-iaas        
      - name: Checkout azure-quickstart-templates
        uses: actions/checkout@v2
        with:
          repository: Azure/azure-quickstart-templates
          path: azure-quickstart-templates     
      - name: Checkout arm-oraclelinux-wls-admin
        uses: actions/checkout@v2
        with:
          path: arm-oraclelinux-wls-admin  
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build azure-javaee-iaas
        run: mvn -DskipTests clean install --file azure-javaee-iaas/pom.xml
      - name: Built and test arm-oraclelinux-wls-admin
        run: mvn -Ptemplate-validation-tests clean install --file arm-oraclelinux-wls-admin/pom.xml  
        
      - name: Get version information from pom.xml
        id: version
        run: echo "##[set-env name=version;]$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' arm-oraclelinux-wls-admin/pom.xml)"
      - name: Print version
        run: echo $version 
      - name: Generate artifact name         
        run: echo "##[set-env name=artifactName;]arm-oraclelinux-wls-admin-$version-arm-assembly"  
      - name: Print artifact name
        run: echo $artifactName
      - name: Output artifact name
        id: artifact_file
        run: echo "##[set-output name=artifactName;]arm-oraclelinux-wls-admin-$version-arm-assembly"
      - name: Generate zip package path
        id: artifact_path
        run: echo "##[set-output name=artifactPath;]arm-oraclelinux-wls-admin/target/$artifactName"
      - name: Output artifact path
        run: echo $artifactPath
        env: 
          artifactPath: ${{steps.package.outputs.artifactPath}}
      - name: Unzip the package as upload action will zip again 
        run: unzip arm-oraclelinux-wls-admin/target/$artifactName.zip -d arm-oraclelinux-wls-admin/target/$artifactName

      - name: Archive arm-oraclelinux-wls-admin target
        uses: actions/upload-artifact@v1 
        if: success()
        with:
          name: ${{steps.artifact_file.outputs.artifactName}}
          path: ${{steps.artifact_path.outputs.artifactPath}}